//
//  HomeInteractor.swift
//  Clicks!
//
//  Created by Leonel Menezes on 24/05/2018.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
  func fetchOpenChallenges(request: Home.GetOpenChallenges.Request)
}

protocol HomeDataStore
{
    var openChallenges : [Challenge]? { get }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var openChallenges: [Challenge]?
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
  
  // MARK: Do something
  
  func fetchOpenChallenges(request: Home.GetOpenChallenges.Request)
  {
    worker = HomeWorker()
    worker?.fetchOpenChallenges(apiSecret: "", numberOfChallenges: 8, completionHandle: { (challenges) in
        self.openChallenges = challenges
        let response = Home.GetOpenChallenges.Response(openChallenges: challenges)
        self.presenter?.presentOpenChallenges(response: response)
    })
  }
}
