//
//  HomeWorker.swift
//  Clicks!
//
//  Created by Leonel Menezes on 24/05/2018.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker
{
    func fetchOpenChallenges(apiSecret: String, numberOfChallenges: Int, completionHandle: @escaping ([Challenge]) -> Void)
  {
  }
}
