//
//  ChallengeInteractor.swift
//  Clicks!
//
//  Created by Leonel Menezes on 07/10/18.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChallengeBusinessLogic
{
//  func doSomething(request: Challenge.Something.Request)
}

protocol ChallengeDataStore
{
  //var name: String { get set }
}

class ChallengeInteractor: ChallengeBusinessLogic, ChallengeDataStore
{
  var presenter: ChallengePresentationLogic?
  var worker: ChallengeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
//  func doSomething(request: Challenge.Something.Request)
//  {
//    worker = ChallengeWorker()
//    worker?.doSomeWork()
//
//    let response = Challenge.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
}
