//
//  ChallengeModels.swift
//  Clicks!
//
//  Created by Leonel Menezes on 07/10/18.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ChallengeScreen
{
  // MARK: Use cases
  
  enum ChallengeData
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
        enum interactionButtonStatusEnum{
            case participating
            case notParticipating
            case uploadingPhoto
            case noDataYet
        }
        enum challengeStatusEnum{
            case over
            case votationPeriod
            case open
            case noDataYet
        }
        
        var theme: String
        var buttonStatus: interactionButtonStatusEnum
        var challengeStatus: challengeStatusEnum
        var numberOfPhotos: Int
        var winnerPhoto : UIImage?
        struct photo {
            var ownerUserName: String?
            var isNew: Bool
            var photo: UIImage
            var ownerProfileImage: UIImage?
            var numberOfLikes: Int?
        }
        var photos: [photo]
        var favouritePhoto: photo?
        var myPhoto: photo?
    }
  }
}
