//
//  ProfilePresenter.swift
//  Clicks!
//
//  Created by Leonel Menezes on 13/06/2018.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic
{
  
}

class ProfilePresenter: ProfilePresentationLogic
{
  weak var viewController: ProfileDisplayLogic?
  
}
