//
//  ProfileModels.swift
//  Clicks!
//
//  Created by Leonel Menezes on 13/06/2018.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Profile
{
    // MARK: Use cases
    
    enum FetchPhotos
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
            struct User {
                var profileImage : UIImage
                var name: String
                var nickName: String
                var numberOfPhotos: String
                var numberOfTrophies : String
            }
            struct Photo {
                var image: UIImage
                var hasTrophy: Bool
            }
            var photos: [Photo]
        }
    }
    
    enum FetchUser
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
            struct User {
                var profileImage : UIImage
                var name: String
                var nickName: String
                var numberOfPhotos: String
                var numberOfTrophies : String
            }
        }
    }
}

