
//
//  OnboardingModels.swift
//  Clicks!
//
//  Created by Leonel Menezes on 24/05/2018.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Onboarding
{
    // MARK: Use cases
    ///View Model to be shown 
    enum PageStructure {
        struct ViewModel {
            struct SinglePage {
                var imageName: String
                var title: String
                var description: String
            }
            var pages: [SinglePage]
        }
    }
}
