
//
//  OnboardingViewController.swift
//  Clicks!
//
//  Created by Leonel Menezes on 24/05/2018.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnboardingDisplayLogic: class
{
    func displaySomething(viewModel: Onboarding.PageStructure.ViewModel)
}

class OnboardingViewController: UICollectionViewController, OnboardingDisplayLogic, UICollectionViewDelegateFlowLayout
{
    
    private var prevIndex: Int = 0
    var interactor: OnboardingBusinessLogic?
    var router: (NSObjectProtocol & OnboardingRoutingLogic & OnboardingDataPassing)?
    private let imageView : UIImageView = {
        let imageView = UIImageView()
        imageView.translatesAutoresizingMaskIntoConstraints = false
        imageView.clipsToBounds = true
        imageView.contentMode = .center
        return imageView
    }()
    private let pageControl : UIPageControl = {
       let pc = UIPageControl()
        pc.currentPage = 0
        pc.numberOfPages = 4
        pc.currentPageIndicatorTintColor = AppColors.clearblack.color
        pc.pageIndicatorTintColor = .gray
        pc.translatesAutoresizingMaskIntoConstraints = false
        return pc
    }()
    private let rightButton : UIButton = {
        let skipButton = UIButton()
        skipButton.setTitle(NSLocalizedString("SKIP", comment: ""), for: .normal)
        skipButton.setTitleColor(AppColors.clearblack.color, for: .normal)
        skipButton.titleLabel?.font = UIFont(name: "Montserrat-Medium", size: 13)
        skipButton.addTarget(self, action: #selector(handleSkip), for: .touchUpInside)
        skipButton.translatesAutoresizingMaskIntoConstraints = false
        return skipButton
    }()
    private let leftButton : UIButton = {
        let prevButton = UIButton()
        prevButton.translatesAutoresizingMaskIntoConstraints = false
        return prevButton
    }()
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    override init(collectionViewLayout layout: UICollectionViewLayout) {
        super.init(collectionViewLayout: layout)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = OnboardingInteractor()
        let presenter = OnboardingPresenter()
        let router = OnboardingRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    @objc func handleSkip() {
        print("trying to skip")
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
        setupCollectionView()
        setupImageView()
        setupBottomControls()
        self.view.backgroundColor = AppColors.darkwhite.color
    }
    override var prefersStatusBarHidden: Bool {
        return true
    }
    
    // MARK: - SCROLL VIEW
    override func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
        let x = targetContentOffset.pointee.x
        let pageIndex = Int(x/view.frame.width)
        self.pageControl.currentPage = pageIndex
        if(self.prevIndex != pageIndex){
            switchImageAnimation(imageIndex: pageIndex + 1)
            prevIndex = pageIndex
        }
        if(pageIndex == 3){
            self.rightButton.setTitle(NSLocalizedString("LET'S GO", comment: ""), for: .normal)
        }else {
            self.rightButton.setTitle(NSLocalizedString("SKIP", comment: ""), for: .normal)
        }
    }
    
    // MARK: - Collection View
    
    func setupCollectionView() {
        collectionView?.backgroundColor = AppColors.darkwhite.color
        collectionView?.isPagingEnabled = true
        collectionView?.showsHorizontalScrollIndicator = false
        //Registers the collection view page cells
        collectionView?.register(PageCell.self, forCellWithReuseIdentifier: "cellID")
        collectionView?.translatesAutoresizingMaskIntoConstraints = false
        collectionView?.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        collectionView?.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        collectionView?.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        collectionView?.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
    }
    
    override func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 4
    }
    
    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cellID", for: indexPath) as! PageCell
        interactor?.accessPageData(pageNumber: indexPath.item, completionHandler: { (structure) in
            cell.holders = structure
        })
        
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: collectionView.frame.width, height: collectionView.frame.height)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return 0
    }
    
    // MARK: Do something
    
    func doSomething()
    {
        
    }
    
    func displaySomething(viewModel: Onboarding.PageStructure.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    
    
    func setupImageView()  {
        self.view.addSubview(self.imageView)
        self.imageView.topAnchor.constraint(equalTo: self.view.topAnchor).isActive = true
        self.imageView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor).isActive = true
        self.imageView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor).isActive = true
        self.imageView.heightAnchor.constraint(equalTo: self.view.heightAnchor, multiplier: 0.63).isActive = true
        self.imageView.image = UIImage(named: "imageOnboard1")
    }
    
    func setupBottomControls() {
        let stackViewBottomControls = UIStackView(arrangedSubviews: [ self.leftButton, self.pageControl, self.rightButton])
        stackViewBottomControls.translatesAutoresizingMaskIntoConstraints = false
        stackViewBottomControls.distribution = .fillEqually
        self.view.addSubview(stackViewBottomControls)
        NSLayoutConstraint.activate([
            stackViewBottomControls.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor),
            stackViewBottomControls.centerXAnchor.constraint(equalTo: self.view.centerXAnchor),
            stackViewBottomControls.trailingAnchor.constraint(equalTo: self.view.trailingAnchor),
            stackViewBottomControls.leadingAnchor.constraint(equalTo: self.view.leadingAnchor)
            ])
    }
    
    // MARK: - Animations
    
    func switchImageAnimation(imageIndex: Int) {
        UIView.animate(withDuration: 0.2, delay: 0, options: .curveLinear, animations: {
            self.imageView.alpha = 0
        }, completion: { finished in
            
            self.imageView.image = UIImage(named: "imageOnboard\(imageIndex)")
            
            UIView.animate(withDuration: 0.2, delay: 0, options: .curveLinear, animations: {
                self.imageView.alpha = 1
            }, completion: { finished in })
        })
    }
}
