//
//  OnboardingRouter.swift
//  Clicks!
//
//  Created by Leonel Menezes on 24/05/2018.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol OnboardingRoutingLogic
{
    func skipOnboarding()
}

protocol OnboardingDataPassing
{
    var dataStore: OnboardingDataStore? { get }
}

class OnboardingRouter: NSObject, OnboardingRoutingLogic, OnboardingDataPassing
{
    weak var viewController: OnboardingViewController?
    var dataStore: OnboardingDataStore?

    func skipOnboarding() {
        let homeVC = UIStoryboard(name: "HomeScreen", bundle: nil).instantiateViewController(withIdentifier: "Home")
        viewController?.navigationController?.pushViewController(homeVC, animated: true)
    }
}

