//
//  MainScreenInteractor.swift
//  Clicks!
//
//  Created by Leonel Menezes on 12/06/2018.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainScreenBusinessLogic
{
//    func doSomething(request: MainScreen.Something.Request)
    func fetchOpenChallenges(request: MainScreen.OpenChallenges.Request)
}

protocol MainScreenDataStore
{
    //var name: String { get set }
    var openChallenges: MainScreen.OpenChallenges.ViewModel.OpenChallenges? {get}
}

class MainScreenInteractor: MainScreenBusinessLogic, MainScreenDataStore
{
    var openChallenges: MainScreen.OpenChallenges.ViewModel.OpenChallenges?
    
    var presenter: MainScreenPresentationLogic?
    var worker: MainScreenWorker?
    //var name: String = ""
    
    // MARK: Do something
    func fetchOpenChallenges(request: MainScreen.OpenChallenges.Request) {
        
    }
//    func doSomething(request: MainScreen.Something.Request)
//    {
//        worker = MainScreenWorker()
//        worker?.doSomeWork()
//        
//        let response = MainScreen.Something.Response()
//        presenter?.presentSomething(response: response)
//    }
}

