//
//  MainScreenPresenter.swift
//  Clicks!
//
//  Created by Leonel Menezes on 12/06/2018.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainScreenPresentationLogic
{
    func presentSomething(response: MainScreen.Something.Response)
}

class MainScreenPresenter: MainScreenPresentationLogic
{
    weak var viewController: MainScreenDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: MainScreen.Something.Response)
    {
        let viewModel = MainScreen.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}

