//
//  PhotosSlideScreenInteractor.swift
//  Clicks!
//
//  Created by Leonel Menezes on 14/09/2018.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosSlideScreenBusinessLogic
{
//  func doSomething(request: PhotosSlideScreen.Something.Request)
}

protocol PhotosSlideScreenDataStore
{
  //var name: String { get set }
}

class PhotosSlideScreenInteractor: PhotosSlideScreenBusinessLogic, PhotosSlideScreenDataStore
{
  var presenter: PhotosSlideScreenPresentationLogic?
  var worker: PhotosSlideScreenWorker?
  //var name: String = ""
  
  // MARK: Do something
//  
//  func doSomething(request: PhotosSlideScreen.Something.Request)
//  {
//    worker = PhotosSlideScreenWorker()
//    worker?.doSomeWork()
//    
////    let response = PhotosSlideScreen.Something.Response()
////    presenter?.presentSomething(response: response)
//  }
}
