//
//  PhotosSlideScreenPresenter.swift
//  Clicks!
//
//  Created by Leonel Menezes on 14/09/2018.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosSlideScreenPresentationLogic
{

}

class PhotosSlideScreenPresenter: PhotosSlideScreenPresentationLogic
{
  weak var viewController: PhotosSlideScreenDisplayLogic?
  
}
